package com.example.ucmconnectapi.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * DTO for Post entity
 * Used for both request and response
 *
 * Note: Fields marked as READ_ONLY in schema are ignored in POST/PUT requests
 */
@Schema(description = "Post details")
public class PostDTO {

    @Schema(description = "Post UUID (ignored in requests, generated by server)", example = "550e8400-e29b-41d4-a716-446655440000", accessMode = Schema.AccessMode.READ_ONLY)
    private UUID id;

    @Schema(description = "Post title", example = "Data Structures Cheat Sheet", requiredMode = Schema.RequiredMode.REQUIRED)
    @NotBlank(message = "Title is required")
    @Size(min = 3, max = 255, message = "Title must be between 3 and 255 characters")
    private String title;

    @Schema(description = "Post description", example = "Complete guide to trees and graphs")
    @Size(max = 2000, message = "Description cannot exceed 2000 characters")
    private String description;

    @Schema(description = "User ID who created the post (comes from auth header)", accessMode = Schema.AccessMode.READ_ONLY)
    private UUID userId;

    @Schema(description = "Username of post creator", example = "Adam", accessMode = Schema.AccessMode.READ_ONLY)
    private String userName;

    @Schema(description = "Subject ID (optional)", example = "550e8400-e29b-41d4-a716-446655440000")
    private UUID subjectId;

    @Schema(description = "Subject name", example = "Computer Science", accessMode = Schema.AccessMode.READ_ONLY)
    private String subjectName;

    @Schema(description = "File type", example = "pdf", allowableValues = {"pdf", "image", "zip"}, accessMode = Schema.AccessMode.READ_ONLY)
    private String fileType;

    @Schema(description = "File URL/path", example = "mock-file.pdf", accessMode = Schema.AccessMode.READ_ONLY)
    private String fileUrl;

    @Schema(description = "File size in bytes", example = "0", accessMode = Schema.AccessMode.READ_ONLY)
    private Long fileSize;

    @Schema(description = "Number of likes", example = "0", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer numberOfLikes;

    @Schema(description = "Number of comments", example = "0", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer numberOfComments;

    @Schema(description = "Is post published", example = "true", accessMode = Schema.AccessMode.READ_ONLY)
    private Boolean isPublished;

    @Schema(description = "Creation timestamp", example = "2025-10-12T10:30:00", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime createdAt;

    @Schema(description = "Last update timestamp", example = "2025-10-12T14:20:00", accessMode = Schema.AccessMode.READ_ONLY)
    private LocalDateTime updatedAt;

    // Constructors
    public PostDTO() {
    }

    // Getters and Setters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public UUID getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(UUID subjectId) {
        this.subjectId = subjectId;
    }

    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getFileUrl() {
        return fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public Integer getNumberOfLikes() {
        return numberOfLikes;
    }

    public void setNumberOfLikes(Integer numberOfLikes) {
        this.numberOfLikes = numberOfLikes;
    }

    public Integer getNumberOfComments() {
        return numberOfComments;
    }

    public void setNumberOfComments(Integer numberOfComments) {
        this.numberOfComments = numberOfComments;
    }

    public Boolean getIsPublished() {
        return isPublished;
    }

    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
